/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "inverse-primary": "#b4c5ff",
        "error": "#ba1a1a",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "outline": "#737686",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0053db",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-container": "#fffbff",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#c3c6d7",
        "on-secondary-fixed": "#25005a",
        "tertiary-container": "#656d84",
        "background": "#f7f9fb",
        "tertiary": "#4d556b",
        "secondary-fixed": "#eaddff",
        "on-error-container": "#93000a",
        "secondary-container": "#8a4cfc",
        "primary-fixed": "#dbe1ff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#bec6e0",
        "on-primary": "#ffffff",
        "surface": "#f7f9fb",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary-fixed-variant": "#5a00c6",
        "primary-container": "#2563eb",
        "on-tertiary-fixed-variant": "#3f465c",
        "primary-fixed-dim": "#b4c5ff",
        "primary": "#004ac6",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-fixed": "#00174b",
        "on-background": "#191c1e",
        "on-tertiary-container": "#eef0ff",
        "secondary": "#712ae2",
        "on-tertiary-fixed": "#131b2e",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#dae2fd",
        "on-surface-variant": "#434655",
        "surface-dim": "#d8dadc",
        "on-primary-container": "#eeefff",
        "surface-variant": "#e0e3e5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "base": "8px",
        "gutter": "16px",
        "container-padding": "24px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "title-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
